### ISSUE TITLE
Source code for "hekate_ctcaer_5.1.4_J.bin" still missing

### ISSUE THREAD

**Issue by borntohonk** [Joonie86/hekate#4]
I see you've taken initiative to push the source code from latest master! However, it seems it's missing the aforementioned "hardcoded patch". Would you mind addressing this mistake?

**Comment by Joonie86** [comment]
> I see you've taken initiative to push the source code from latest master! However, it seems it's missing the aforementioned "hardcoded patch". Would you mind addressing this mistake?

https://github.com/Joonie86/hekate/blob/master/bootloader/hos/pkg2.c#L597
^ this was addressed in the released note.

**Comment by borntohonk** [comment]
I see, but it is missing the justification you've provided in the release note. Clearly some kind of mistake.

**Comment by borntohonk** [comment]
https://github.com/CTCaer/hekate/blob/master/bootloader/hos/pkg2.c#L639
https://github.com/CTCaer/hekate/blob/master/bootloader/hos/pkg2.c#L640
The sha256 of both fs.kip1 are in hekate master, I don't see why it would not load the provided "hardcoded patches", if they were not provided in patches.ini

**Comment by borntohonk** [comment]
They'd both natively load under

[FS:3EEBD9B7BCD1B5E0]
[FS:817EA2B0B702C1F3]

**Comment by Joonie86** [comment]
> They'd both natively load under @Joonie86
> 
> [FS:3EEBD9B7BCD1B5E0]
> [FS:817EA2B0B702C1F3]

I wouldn't have forked this hekate again if that worked fine. even with the correct hashes it still fails to apply.
