### ISSUE TITLE
Error on boot - Failed to apply 'nosigchk'

### ISSUE THREAD

**Issue by kacciocciacciara** [Joonie86/hekate#6]
So, today I updated my switch to the firmare 10.0.0 (didn't burn the fuses from 9.2.0), updated hekate to version 5.1.4 and Kosmos to version 15.5, and applied the latest patches (17-04-2020).
After the process, when I try to boot atmosphere from SYSNAND, the screen goes black with red text saying:

Failed to apply 'nosignchk'!
Failed to launch HOS!
Press any key...

I tried to remove the line "kip1patch=nosigchk" but then the console crashes before the atmosphere splash screen.
Any suggestion?

**Comment by Joonie86** [comment]
looks like you're not injecting the modified payload that's included in the release section.

**Comment by kacciocciacciara** [comment]
That was a rookie mistake.
Ok, nontheless, after using the latest payload the console goes black screen after "sept by atmosphere". I have to force the shutdown and re inject the payload.

**Comment by Joonie86** [comment]
> That was a rookie mistake.
> Ok, nontheless, after using the latest payload the console goes black screen after "sept by atmosphere". I have to force the shutdown and re inject the payload.

Not sure what is wrong, you have to make sure that you have a working kosmos before applying patches. Please clean your SDCard and start from the scratch.  Once kosmos is booting fine then apply patches. Just to isolate the issue.

**Comment by kacciocciacciara** [comment]
Double rookie mistake.
Downloaded the "+tinfoil" package, updated the file "ams_mitm.kip", now it works.
Thanks for your quick replies! :)
